### ISSUE TITLE
Thumbnail image for audio files?

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#10]
It will make it easier to find an audio file if it has a thumbnail image, right? 👍™
![image](https://user-images.githubusercontent.com/93544997/196008363-2bdbdcfb-c2da-409f-9b1d-2158aaaf6cbc.png)

**Comment by nlogozzo** [comment]
Since Tube Converter utilizes yt-dlp as it's backend, I will have to check how (if its possible) to implement this feature.

**Comment by nlogozzo** [comment]
In the mean time, I do have another application known as [Tagger](https://beta.flathub.org/apps/details/org.nickvision.tagger) that can be used to easily add tag metadata, including cover art, to audio files.

**Comment by fawaz006** [comment]
> Since Tube Converter utilizes yt-dlp as it's backend, I will have to check how (if its possible) to implement this feature.

I forget to mention that the file with the thumbnail it's downloaded from [jely2002/youtube-dl-gui](https://github.com/jely2002/youtube-dl-gui) which also use yt-dlp

**Comment by nlogozzo** [comment]
Please test: https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.3-beta1

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/196079349-8a48311f-8796-496a-852d-a186a7db374d.png)

Note: This setting can be controlled in the preferences dialog (It is on by default)

**Comment by fawaz006** [comment]
It's now working and showing the thumbnail image
![image](https://user-images.githubusercontent.com/93544997/196139796-9db12706-be17-4099-805e-2a32b7a286f8.png)
But I think the 3gp.part file should be deleted after the downloading.
