### ISSUE TITLE
Legacy file picker

### ISSUE THREAD

**Issue by freyq** [nlogozzo/NickvisionTubeConverter#108]
The application seems to be using a somehow legacy variant/implementation of the file picker for Nautilus which leads to it disrespecting global dark/light mode and only follows the themes explicitly set in Tweaks for Legacy Applications. Setting this up is propably inconvient for most users as (at least in Arch) the legacy themes have to be installed specifically and are not included by default in Gnome.

**Comment by nlogozzo** [comment]
@fsobolev ?

**Comment by fsobolev** [comment]
If you are using package from AUR, the app uses Gtk.FileDialog. If you use Flatpak, the app uses Gtk.FileChooserNative for now, it will be changed to Gtk.FileDialog too when GTK 4.10 will be available in flatpak runtime.
But in any case, both FileDialog and FileChooserNative call whatever file chooser is native for your system. So on KDE it will be KDE's file chooser. And in your case... What DE do you use?

**Comment by fsobolev** [comment]
Seems like [there's no way](https://www.github.com/flatpak/flatpak/issues/3977) to disable file chooser portal access, I tried on XFCE to play around with GTK_USE_PORTAL=0, XDG_CURRENT_DESKTOP=GNOME and `--no-talk-name="org.freedesktop.potal.FileChooser"`, but no changes, always XFCE file chooser appears.
@nlogozzo should we close this as "won't fix" and "not our bug"?

**Comment by nlogozzo** [comment]
I guess so
