### ISSUE TITLE
Subtitle support?

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#11]
It will be great to add auto subtitle downloader in the options and make it (SRT)+(embedded) because many apps have an option to download a subtitle, but they downloaded as VTT which you should convert it to SRT to use on old machines 👍

**Comment by nlogozzo** [comment]
[Screencast from 10-17-2022 12:18:44 AM.webm](https://user-images.githubusercontent.com/17648453/196088602-290a8a8a-914a-44e0-84f2-c7ddf318cc82.webm)

**Comment by nlogozzo** [comment]
Some development progress. Going to add support for VTT or SRT subtitles. 
Tube Converter will check if subtitles are available first and if not, it will change the option in the dialog back to None as shown above.

**Comment by nlogozzo** [comment]
Please test: https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.3-beta2
Selecting a type of subtitles for an audio file has no effect. See known issues in the release for more information ^

**Comment by ovari** [comment]
If a video has subtitles in multiple languages, does it download all the languages or can the required languages be selected?

Thank you

**Comment by fawaz006** [comment]
> If a video has subtitles in multiple languages, does it download all the languages or can the required languages be selected?

I think you should choose the languages once on the setting, and then forget about it.
Right? @nlogozzo

**Comment by nlogozzo** [comment]
If a video gas multiple language subtitles, it will download and embed all language subtitles into the video file. A specific language can be chosen from the video player itself.

**Comment by nlogozzo** [comment]
@fawaz006 can you send me the link of the video you are using. Some videos are just un-downloadable sometimes.

**Comment by fawaz006** [comment]
https://www.youtube.com/watch?v=NUYvbT6vTPs

**Comment by nlogozzo** [comment]
webm works too...try closing the application and running the download again.

**Comment by fawaz006** [comment]
Hmm… The old father's technic are working again. (I mean closing the and open it)

**Comment by fawaz006** [comment]
But still haven't downloaded the subtitle yet.

**Comment by nlogozzo** [comment]
Let me try subtitles...

**Comment by nlogozzo** [comment]
That is because the video has no subtitles:
![image](https://user-images.githubusercontent.com/17648453/196181194-c394e35b-b502-4c62-811d-e846ca484458.png)

Tube Converter reports incorrectly that it does. Let me fix that.

**Comment by fawaz006** [comment]
I forget to mention that I mean the (Subtitle) + (Auto translated Subtitle)

**Comment by fawaz006** [comment]
And I think yt-dlp support it because many yt-dlp based apps have this feature

**Comment by nlogozzo** [comment]
Ok, I will make it where auto generated subtitles will be used if no real subtitles are found.

**Comment by fawaz006** [comment]
+ Auto translated Subtitle 🥺

**Comment by nlogozzo** [comment]
[V2022.10.3](https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.3)
Known Issue: Can't select language so Tube Converter will embed all auto-generated language subtitles if no real subtitles are found. 
Don't know what I will do about this yet. Might just leave it since you'll be able to select the subtitle language from your video player.

**Comment by fawaz006** [comment]
But do you think it's little exaggerated to download ALL the languages on one video.

![image](https://user-images.githubusercontent.com/93544997/196251758-ef8b00a2-52d3-4af8-be69-1d537d9f5269.png)


![image](https://user-images.githubusercontent.com/93544997/196251771-03830d05-5f67-4aca-b3af-59e28dbf49fb.png)

**Comment by nlogozzo** [comment]
I agree it does suck that it downloads subtitles for every language available which can take a lot of bandwidth, however it's the best I can do right now.

It's going to take a while to implement proper language selection as I need to find a way to parse the output of available subtitles to allow the user to select from.
Or another way I could implement it is to have the user provide the language they want and if it is not available simply say no subtitles available.
