### ISSUE TITLE
[Windows] Unable to change the file destination folder

### ISSUE THREAD

**Issue by LightNeko** [nlogozzo/NickvisionTubeConverter#113]
The title says all. When it is asked to choose the destination folder for the downloaded file, nothing happens when I click on the green button, and I can't even insert the path manually.

I am on Windows 10 and using version 2023.3.0.

**Comment by nlogozzo** [comment]
> I can't even insert the path manually

This is by design to ensure users always select a valid destination folder via the FolderPicker to give the app access to that folder

> I am on Windows 10

What version of Windows 10 are you using?

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/226908175-486c4759-34a2-44c6-b10e-56f2a11ebd47.png)

So you are saying clicking on this button does nothing?

All it does is just opens a simple uwp `FolderPicker`:
```csharp
var folderPicker = new FolderPicker();
var fileType = (MediaFileType)CmbFileType.SelectedIndex;
_initializeWithWindow(folderPicker);
folderPicker.SuggestedStartLocation = fileType.GetIsVideo() ? PickerLocationId.VideosLibrary : PickerLocationId.MusicLibrary;
var folder = await folderPicker.PickSingleFolderAsync();
```

I'm using Windows 11 and don't have a Windows 10 system...but WindowsAppSDK should work on both.

**Comment by LightNeko** [comment]
Can't say what difference can be there between windows 10 and windows 11, but yes, when I click that button it does nothing (the application crashed once, but I could not reproduce the crash again). 

Don't know if it is an useful information, but my system and the application are in Italian language.

I should try with a different windows 10 system and check if it is only on my pc, but I can't do that for now.

**Comment by LightNeko** [comment]
> Ora possiamo essere amici ;)

ahah con molto piacere! :)

Anyway, I have "video e musica" in Italian, and so far I have had no issue with downloading and other features, everything works fine, except that I can't change folder.

**Comment by nlogozzo** [comment]
I don't see why you can't change the folder 🤔 I'll do some more investigating tonight when I get some free time

**Comment by nlogozzo** [comment]
Weird how it's not requires for 11 but for 10 it is....but it's Microsoft I'm not surprised haha

Anyway...thanks for the fix :)

**Comment by Tweekism** [comment]
I think you probably get a different style folder picker dialog in Windows 11, like an updated one that's more Windows eleveny and stuff...

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.0

*Should be available sometime today or tomorrow on the store :)*
