### ISSUE TITLE
Media titles with filesystem-illegal characters are not handled/truncated.

### ISSUE THREAD

**Issue by Mycohl** [nlogozzo/NickvisionTubeConverter#120]
Steps to repro:

1. Attempt to download a video with a title which includes an illegal character (slash, asterisk, etc)
2. Do not manually edit title

Result:
File is saved with incorrect title, or is not saved at all, depending on which illegal character appears in title.

Expected:
Illegal characters in title will prevent download with message, or be auto-converted to placeholder character, such as "!".

Note: Please do not search YouTube for punctuation marks, because this functionality has been ruined by a meme.
Instead, here are some example videos:
- https://www.youtube.com/watch?v=h1r7pfWyY_g
-- Illegal character: *
-- Result: File is not saved
- https://www.youtube.com/watch?v=XNUXp0R6FEg
-- Illegal character: /
-- Result: Filename is truncated

**Comment by nlogozzo** [comment]
Could probably use this: https://www.reddit.com/r/youtubedl/comments/yz9ozo/how_do_i_get_ytdlp_downloads_without_forbidden/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by Mycohl** [comment]
> Could probably use this: https://www.reddit.com/r/youtubedl/comments/yz9ozo/how_do_i_get_ytdlp_downloads_without_forbidden/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Could also manually check and edit every offending filename in a 100-entry playlist. The user shouldn't have to manually fix anything, or edit a .desktop file. The app should catch this sort of thing without user intervention.

**Comment by nlogozzo** [comment]
> Could also manually check and edit every offending filename in a 100-entry playlist. 

This isn't a good idea since we can add a simple flag to yt-dlp backend to do it for us.

> The user shouldn't have to manually fix anything, or edit a .desktop file. The app should catch this sort of thing without user intervention.

I don't know what you mean by this...but the app will when the feature is implemented. I don't know what a .desktop file has to do with anything

**Comment by Mycohl** [comment]
> This isn't a good idea since we can add a simple flag to yt-dlp backend to do it for us.

I agree. I brought it up in response to the offered solution. The point of using a front-end is to do the work for the user, not vice-versa.

> I don't know what you mean by this...but the app will when the feature is implemented. I don't know what a .desktop file has to do with anything

When the solution of passing an argument to yt-dlp was offered, I assume most Linux users would do that consistently by editing the .desktop file and hoping the app passes the argument on. (This is not obvious, as I stated in my edit.)

**Comment by nlogozzo** [comment]
Sorry didn't mean to edit ur comment 😆 ^

**Comment by fsobolev** [comment]
> The user could also manually check and edit every offending filename in a 100-entry playlist.

100-entry playlist metadata will probably be loading for the eternity, so it will not even be possible to edit anything 😄 

> Also, I cannot find any documentation that states whether flags passed to flatpak/TubeConverter are in turn passed to yt-dlp, so this behavior is non-obvious.

Nothing from start command is passed to yt-dlp, yt-dlp's settings are hard-coded.

**Comment by Mycohl** [comment]
> > Also, I cannot find any documentation that states whether flags passed to flatpak/TubeConverter are in turn passed to yt-dlp, so this behavior is non-obvious.
> 
> Nothing from start command is passed to yt-dlp, yt-dlp's settings are hard-coded.

I'm not sure why this was offered as a solution, in that case.

**Comment by nlogozzo** [comment]
> > > Also, I cannot find any documentation that states whether flags passed to flatpak/TubeConverter are in turn passed to yt-dlp, so this behavior is non-obvious.
> > 
> > Nothing from start command is passed to yt-dlp, yt-dlp's settings are hard-coded.
> 
> I'm not sure why this was offered as a solution, in that case.

It's hard-coded as we pass the arguments ourself...

**Comment by fsobolev** [comment]
> I'm not sure why this was offered as a solution, in that case.

It wasn't offered as a solution for you, it was mentioned like possible solution for us, developers, to investigate and, if it works, implement in the app.

**Comment by Mycohl** [comment]
> It wasn't offered as a solution for you, it was mentioned like possible solution for us, developers, to investigate and, if it works, implement in the app.

My mistake. I'm used to being told that bugs I file are not really bugs, but user error, so I understood that comment as instructions on how to fix the problem.

**Comment by nlogozzo** [comment]
@fsobolev Do you think you could squeeze this in with `--restrict-filenames` then I'll do the V2023.3.1 release?

**Comment by nlogozzo** [comment]
Or maybe use the replace in metadata parameter instead because it looks like restrict filenames replace spaces with underscores which may be unwanted.

**Comment by fsobolev** [comment]
according to docs, `restrictfilenames` disallow only "&" and spaces, let's see...

**Comment by fsobolev** [comment]
New behavior implemented in #127:
1. Invalid filename characters are automatically replaced with `_` and it's impossible to manually add them when editing a title (on Linux only `/` is considered an invalid character)
2. Special characters get escaped when saving a file (only on Linux, on Windows it's not needed)

Example:

![Escaped characters](https://user-images.githubusercontent.com/117388856/228035151-4e026787-c28d-48eb-9f1d-ea4e48fe7884.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.1

**Comment by matrox471** [comment]
Looks like the issue is still present.
Currently, i am using Parabolic 2025.10.3 (flatpak version)
adding the following video result in a file being incorrectly named 
https://www.youtube.com/watch?v=SD_bg2VRTAc
In my case, the target path/filename result in `$target/@echo.%0^|%0›$^_^.c^md&/$commandtolaunchparabolic.extension`





<img width="644" height="633" alt="Image" src="https://github.com/user-attachments/assets/f188319e-5b6e-49ad-bfc6-56e0c85a0036" />
<img width="657" height="633" alt="Image" src="https://github.com/user-attachments/assets/a31a6916-72e9-4776-82c0-e5c5751a9ce1" />
<img width="414" height="99" alt="Image" src="https://github.com/user-attachments/assets/03049e55-2c7e-4d60-8b4f-5ab9b5baa2c2" />
