### ISSUE TITLE
On car's mp3 player it takes 3-4 seconds to play downloaded mp3 file.

### ISSUE THREAD

**Issue by ayhanarf** [nlogozzo/NickvisionTubeConverter#122]
After the latest update, usually takes some time (~3 seconds) to start playing downloaded mp3 file of any quality in the cars mp3 player.

**Comment by nlogozzo** [comment]
@fsobolev 
I don't see what this would have to do with Tube Converter 🤔

Maybe your car takes time to load metadata. Do you have `Embed Metadata` turned on in Settings/Preferences? Try turning it off and see if that helps...But that's all I can really think of, I don't think this is a Tube Converter issue.

**Comment by fsobolev** [comment]
> I don't see what this would have to do with Tube Converter 🤔

We use more recent versions of yt-dlp and ffmpeg now, so I believe it can be caused by one of them.
The only issue that I found that may be related (but I'm not sure) is this: https://trac.ffmpeg.org/ticket/10163
