### ISSUE TITLE
Issues with Youtube Music Playlists

### ISSUE THREAD

**Issue by coreybruce** [nlogozzo/NickvisionTubeConverter#129]
Hey I just wanted to report that it has issues downloading Youtube Music playlists and hoping this could get fixed.

Currently if I try and download a playlist, even one with only 22 songs it will just sit there loading than eventually crash

![image](https://user-images.githubusercontent.com/8393780/228131002-e9478da3-d838-426d-b881-efb366ed84ca.png)

**Comment by nlogozzo** [comment]
Are you running the app via flatpak, snap, or built manually?

If you run the app from a terminal and perform the same action, is there any warning/error output?

**Comment by coreybruce** [comment]
Flatpak 

God damn, it's like it new I  was making this bug report and now it's all of a sudden working but idk why :laughing:

Keep this open, if I catch it I will show you the log. :stuck_out_tongue:

**Comment by coreybruce** [comment]
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/org.nickvision.tubeconverter org.nickvision.tubeconverter

(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 16:34:56.358: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionTubeConverter.GNOME:2): Gtk-CRITICAL **: 16:34:56.358: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_attributes: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_alignment: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_wrap: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_tabs: assertion 'PANGO_IS_LAYOUT (layout)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_get_width: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): GLib-GObject-CRITICAL **: 16:37:12.634: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_set_width: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): Pango-CRITICAL **: 16:37:12.634: pango_layout_get_extents: assertion 'layout != NULL' failed

(NickvisionTubeConverter.GNOME:2): GLib-GObject-CRITICAL **: 16:37:12.634: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
**
Gtk:ERROR:../gtk/gtkcssnode.c:322:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)
Bail out! Gtk:ERROR:../gtk/gtkcssnode.c:322:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)
```

**Comment by nlogozzo** [comment]
Related to NickvisionMoney#401

https://stackoverflow.com/questions/67146064/gtk-crashes-on-adding-and-removing-listboxrows

**Comment by fsobolev** [comment]
> Also noticed it was putting \ in file names

`\` is added to escape special characters - https://github.com/nlogozzo/NickvisionTubeConverter/issues/120#issuecomment-1485679613
But it is probably also added before characters that really don't need to be escaped, like `.` and `?`. 😖

**Comment by coreybruce** [comment]
> 

Hmm so far I am testing it out by downloading 89 songs but it is stuck loading, by the way  not related to this but is there a way to improve loading speeds when it comes to showing all the files and being ready to download? it can take a long time to do this at times. 

This is defiantly a improvement so far, only had one file fail to download and I haven't seen any bugs so far. Also like the file log for each file, that is handy. :) 

Doing a awesome job! :smile: :+1:

**Comment by nlogozzo** [comment]
> by the way not related to this but is there a way to improve loading speeds when it comes to showing all the files and being ready to download? it can take a long time to do this at times.

I've noticed it takes a long time loading playlists too, but I feel like this might be a yt-dlp limitation. I haven't tried downloading a playlist via the command line and comparing it to TC...but I'll look more into it :)

**Comment by nlogozzo** [comment]
Glad the crashing was fixed!

> This is the log also

No big deal, just minor warnings. As long as it doesn't crash looks all good to me :)

**Comment by coreybruce** [comment]
Alight awesome, I'm always glad to help projects out with bug testing @nlogozzo 

I'll be right here if there is more testing needing to be done, just mention me in a issue post!  :smile:

**Comment by coreybruce** [comment]
> > I've noticed it takes a long time loading playlists too, but I feel like this might be a yt-dlp limitation. I haven't tried downloading a playlist via the command line and comparing it to TC...but I'll look more into it :)
> 
> Yes, if you try to get playlist metadata with yt-dlp CLI, it can take a long time: to get metadata for a playlist it loads metadata for each playlist item sequentially, so the time required to load full metadata depends on the number of items in playlist (100 items = a couple of minutes to get metadata?). And I didn't find any hints in docs or issues how to improve this.

Ahh I see and that's not problem, I was just wondering :+1:

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.1

**Comment by quazar-omega** [comment]
Is the speed still a limitation? I tried downloading a YouTube Music album and the validation process took several minutes, I haven't counted how many, but it was slow enough to have me put it in the background, the actual downloading is super fast on the other hand.
I tried downloading the same album with [Video Downloader](https://github.com/Unrud/video-downloader) that is based on yt-dlp too and it didn't take as much time, it was almost instant, do they do fewer checks to achieve this maybe?

**Comment by nlogozzo** [comment]
> Sure, having such option would make sense, but we need to think how to implement it in the UI.

Maybe we can have a setting `Playlist Customization` (on by default). `If enabled, Tube Converter will fetch playlist data to allow customization of each individual media in the playlist. (This may slow down validation of playlists)`

**Comment by nlogozzo** [comment]
I still don't understand why it's painfully slow however, cause it should just be fetching json data for each video in the playlist which is like 1 MB max per video...it shouldn't take as long as it does 🤷‍♂️

**Comment by quazar-omega** [comment]
That sounds good enough, what are the options that would be skipped when disabling the validation of the items though?

**Comment by nlogozzo** [comment]
> That sounds good enough, what are the options that would be skipped when disabling the validation of the items though?

Everything. You'd basically only be able to download the playlist whole and that's it.

You won't be able to change the names of the individual videos when downloading. And you won't be able to select which videos to download from the playlist and which to not, i.e. if a playlist has 5 videos you must download all 5, you won't be able to choose 3/5 for example.

**Comment by quazar-omega** [comment]
I see, but do at least any batch operations remain, like choosing format and the new cropping feature (which is particularly useful for albums)?

**Comment by quazar-omega** [comment]
Oh ok, thanks for clearing that up

**Comment by nlogozzo** [comment]
Use #310 to track :)
