### ISSUE TITLE
Download speed indicator

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#13]
For example:

![image](https://user-images.githubusercontent.com/93544997/196254662-1ca33cf8-d636-4a79-849e-e96c5371c380.png)

![image](https://user-images.githubusercontent.com/93544997/196254695-6ec7492b-0c4a-4802-b6c5-4f1123122de9.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-beta1-p1
