### ISSUE TITLE
[Bug] Files being saved with a backslash in the name

### ISSUE THREAD

**Issue by hyuri** [nlogozzo/NickvisionTubeConverter#133]
Hi!

Files are being saved with a backslash in the name. Example:
**Name:** "Cool youtube video.mp4"
**Saved as:** "Cool youtube video\\.mp4"

Not sure if it's affecting all downloaded files.

**Comment by fsobolev** [comment]
Fixed in #131

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.0
