### ISSUE TITLE
change "url" strings value to uppercase "URL"

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionTubeConverter#134]
because URL is an abbreviation from Uniform Resource Locator, then it should be URL/URLs not Url
![image](https://user-images.githubusercontent.com/92032579/228559985-bcf53f87-3cfe-497c-a911-26a1d4d8128b.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.0
