### ISSUE TITLE
The button to verify URLs is not intuitive

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/NickvisionTubeConverter#139]
## Problem

![Attempting to download a YouTube video](https://user-images.githubusercontent.com/11488886/229180640-b9432970-15b8-433c-8a37-74aee0a232a7.png)

When I paste a YouTube link to "Video URL" input box, I was expecting to download button to become clickable but it didn't which made me confused.

I see the verify button, but at first,  I thought it was a badge, not a button.

### Ideal design

Automatically verify the URL on paste.

### Alternative design

The verify button should be as big and visible as the download button. There is no reason to show a download button when URL hasn't been verified. Once the user clicks the big verify button (and it passes), the verify button should be replaced by the download button.

**Comment by nlogozzo** [comment]
This is the design of all Adwaita entry rows with verification.

We don't want to do automatic verification because everytime the user changes a single character in the text box the UI will re-verify for every little character change. Hence the apply button in the row to say ok I'm down editing the URL, verify it.

**Comment by nlogozzo** [comment]
> The verify button should be as big and visible as the download button. There is no reason to show a download button when URL hasn't been verified. Once the user clicks the big verify button (and it passes), the verify button should be replaced by the download button.

But this sounds like it could be done. Cc @fsobolev

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.0
