### ISSUE TITLE
Unnecessary blackslash in resulting filename

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/NickvisionTubeConverter#141]
When I use Tube Converter to download [WE ARE JAPANESE GOBLIN [MMD]](https://www.youtube.com/watch?v=UIp6_0kct_U), the resulting file is named `WE ARE JAPANESE GOBLIN \[MMD\].mp4` instead of `WE ARE JAPANESE GOBLIN [MMD].mp4`. I can rename the file of course, but it would be super annoying if I was to download multiple videos and then have to rename all of them afterward.

**Comment by fsobolev** [comment]
The reason why special characters are escaped is that otherwise a file will not be saved, see #120 
But I have some thoughts how to handle that a better way to avoid escaping.

**Comment by KSXGitHub** [comment]
ClipGrab doesn't seem to have this issue. I wonder what tricks does it use.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.0
