### ISSUE TITLE
[Feature Request] Playlist Download

### ISSUE THREAD

**Issue by TriVoxel** [nlogozzo/NickvisionTubeConverter#15]
YouTube-DL supports downloading full playlists from YouTube. It would be really cool if your program automatically identified a playlist and downloaded it. Would you be willing to add such a feature? I would really appreciate it as it would be super useful for people trying to backup their favorite music and videos. Thank you for making this program, by the way. It's a really useful tool!

**Comment by nlogozzo** [comment]
Please use #2 to track. 
I need to spend some time thinking about how to change the ux to support playlists.
