### ISSUE TITLE
'Embed Metadata' should be a per-download setting instead of a global setting

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/NickvisionTubeConverter#157]
I think it makes more sense to place "Embed Metadata" setting in the "Add Download" dialog (after clicking the "Validate" button) than to place it in the global "Preferences" dialog.

**Comment by nlogozzo** [comment]
@fsobolev thoughts?

**Comment by fsobolev** [comment]
> @fsobolev thoughts?

Hm... Controversial. On one hand, it would obviously be easier to change the setting for particular downloads if it would be placed in add download dialog. On the other hand, I don't see a reason why a user might want to disable embedding metadata at all, unless there is some bug, in this case the proper solution would be to fix the bug. If the user wants to overwrite metadata, then there's no difference if there will be some metadata or will be none, they will use Tagger or something else anyway. If the goal is to save bandwidth or time, yt-dlp downloads metadata anyway, except for the thumbnail, and I doubt downloading a thumbnail makes much difference.

**Comment by fsobolev** [comment]
> unless there is some bug, in this case the proper solution would be to fix the bug.

And after #163 any problem that can happen with metadata embedding doesn't break downloads, so I would prefer to keep it a global setting.

**Comment by nlogozzo** [comment]
> so I would prefer to keep it a global setting.

Agreed.
