### ISSUE TITLE
Request: For single video (non playlist), the save dialog should choose file instead of choose directory

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/NickvisionTubeConverter#166]
Similar to how "Save As..." works in most applications.

One advantage choosing file as destination instead of directory as destination is that it allows user to determine filename before save.

**Comment by fsobolev** [comment]
> it allows user to determine filename before save.

You can change filename by changing the title of video. It works the same both for single media and for elements of a playlist.

We should probably make it clearer in the UI that title changes filename, not metadata.

**Comment by KSXGitHub** [comment]
But video title IS part of the metadata though. Besides, I think a save file dialog would be more consistent with other applications.
