### ISSUE TITLE
Translator Announces

### ISSUE THREAD

**Issue by sabriunal** [nlogozzo/NickvisionTubeConverter#170]
Hi, could you announce new releases for translators before releasing a new version? 

Most of the time 10 days enough to update translations to new versions.

I think Weblate has a menu for it.

https://docs.weblate.org/en/latest/admin/announcements.html

**Comment by nlogozzo** [comment]
Usually Beta and RC releases are released and announced on GitHub and there is usually a 3-4 day wait period between RC and Stable releases to give translators time to update.

I would add a watch to the github repo to get notifications of new releases. I probably won't remember to add a secondary announcement to Weblate, but I'll try.
