### ISSUE TITLE
Pressing Enter in the 'Add Download' dialog should validate URL, and ESC should "go back"

### ISSUE THREAD

**Issue by KSXGitHub** [nlogozzo/NickvisionTubeConverter#173]
Since the only purpose of the 'Add Download' dialog is to validate the URL, it makes sense that pressing <kbd>Enter</kbd> in the URL should have the same effect as clicking the 'Validate' button. Pressing <kbd>Enter</kbd> again (after the URL is validated successfully) should start the download process (i.e. same effect as the 'Download' button).

Regarding <kbd>ESC</kbd>, pressing it before the URL is validated should close or hide the 'Add Download' dialog, and pressing it after the URL is validated successfully should restore the 'Add Download' dialog to blank (i.e. same effect as the 'Back' button).

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.1
