### ISSUE TITLE
Option for maximum download speed

### ISSUE THREAD

**Issue by lilpea** [nlogozzo/NickvisionTubeConverter#174]
Currently when downloading videos, Tube Converter appears to be using most of my bandwidth, making streaming videos at the same time nearly unusable. An option to limit the download speed would be useful, especially when running the program in the background.

**Comment by fsobolev** [comment]
> @fsobolev sorry for the late reply, but if we're going with #29 I think solving this issue via aria2 would be better? Just a suggestion

It will work for both default downloader and aria2, the same setting will be applied, no problem with that

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.4.2-beta1
