### ISSUE TITLE
Add Playlist Download Feature

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTubeConverter#2]

**Comment by ovari** [comment]
This feature is already available in [Video Downloader](https://github.com/Unrud/video-downloader).

> Download single videos or whole playlists

https://github.com/Unrud/video-downloader#video-downloader

Is there any chance that you can work with @Unrud on [Video Downloader](https://github.com/Unrud/video-downloader) as there is no need to reinvent the wheel?

What do you think?

Thank you

**Comment by nlogozzo** [comment]
[Video Downloader](https://github.com/Unrud/video-downloader) is a different application than Tube Converter. Video Downloader is simple and supported single downloads at a time. Tube Converter was built different. It supports multiple downloads at a time and is highly customizable (supporting video metadata, subtitles, etc...) and will thus remain that way.

**Comment by nlogozzo** [comment]
A mockup by @fsobolev :
![image](https://user-images.githubusercontent.com/17648453/222916238-9a2a214b-e04e-409a-8c41-43365642ba72.png)

*Attaching it here so I don't have to scroll all the way back up in the matrix room 😆*

**Comment by fawaz006** [comment]
It would be nice to add numbering option for the playlist 👍

**Comment by fsobolev** [comment]
> It would be nice to add numbering option for the playlist +1

Do you mean adding a number in a filename?

**Comment by fawaz006** [comment]
> > It would be nice to add numbering option for the playlist +1
> 
> Do you mean adding a number in a filename?

yes

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-rc1
