### ISSUE TITLE
A Few Paper Cuts

### ISSUE THREAD

**Issue by libreajans** [nlogozzo/NickvisionTubeConverter#32]
I found a few paper cuts 

- [x] Support URL does not exist

https://github.com/nlogozzo/NickvisionTubeConverter/blob/main/src/ui/application.cpp#L21

- [x] F1 shortcut/key set to About page.

It's not a big problem but against GNOME HIG.

>Help | F1 | Opens the help app on the page for the app.

https://developer.gnome.org/hig/reference/keyboard.html

- [x] Invalid "Save Folder (Invalid)" Error 😄

It happens when "New File Name" is empty but errors about the folder.

![bug](https://user-images.githubusercontent.com/6218679/201660520-f2e3d576-55d8-4a4c-b30f-09e1f2ea1d71.png)

**Comment by nlogozzo** [comment]
>  Support URL does not exist

Fixed.

> F1 shortcut/key set to About page.

Tube Converter does not have a help page, therefore the closest dialog to find help information would be the About dialog.

> Invalid "Save Folder (Invalid)" Error

New Filename is allowed to be empty. That means that Tube Converter is unable to find the directory you provided:
```cpp
if(!std::filesystem::exists(downloadPath.parent_path()))
{
    return DownloadCheckStatus::InvalidSaveFolder;
}
```

**Comment by libreajans** [comment]
With latest changes it works fine. İndirilenler mean Downloads and the folder is there. I don't know how or why but it fixed now. Thanks.
