### ISSUE TITLE
Date shown in podcast player is 1/1/22 when using mp3 format

### ISSUE THREAD

**Issue by Tater-K7S5A** [nlogozzo/NickvisionTubeConverter#37]
I have been using TubeConverter to download the audio of podcasts and live streams from YouTube channels.  The program does a nice thumbnail and video name.  It works as I would expect except that the downloaded audio shows in my podcast player as 1/1/22 on all mp3 downloads instead of the date of the video or the date it was downloaded.  

This is not a huge deal, but it messes with playing things in order of publication, which is annoying.  I'm using Podcast Addict on Android to play the audio downloads.

I also downloaded one of the video's audio in flac which used the download time as the publication date.  So it's something to do with how Tube Converter is handling mp3.

And:  I used `youtube-dl -i --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=[video id]` (to verify it wasn't an issue with mp3) and it shows a publication date in the podcast player as the download time/date. 

Thank you for making this application.  I really appreciate the effort it takes to make and maintain it.

**Comment by nlogozzo** [comment]
The command Tube Converter uses to download mp3, flac, and any other audio file is

`yt-dlp --extract-audio --audio-format FILE_FORMAT --audio-quality QUALITY https://www.youtube.com/watch?v=[video id] -o FILE_NAME.%(ext)s`

Check if the issue still persists using that command outside of Tube Converter. If it does, I would say it's a yt-dlp/youtube-dl problem.

**Comment by Tater-K7S5A** [comment]
I'm not sure what should be put in "FILE_NAME.%(ext)s"  Leaving it as is throws error "bash: syntax error near unexpected token `(' "

As I have been using TubeConverter I have not been specifying a file name.  So I assume I would need the fall back switch that TubeConverter uses.  TubeConverter has been providing the names the videos are published under perfectly.

After I removed the "FILE_NAME.%(ext)s" and tried again I got "Command 'yt-dlp' not found, but can be installed with:
sudo apt install yt-dlp"  Which tells me that maybe I am not running the youtube-dl that the application is using?

I installed yt-dlp and ran the command again. It didn't like the file name either and chastised me for -o without an argument.

I ditched the -o and ran it.  I got a file with a name including the video name and the alphabet soup identifier.  It showed a publication date of a few seconds when I put i in the podcast player.  

Something in Tube Converter (When run without specifying a file name?) is messing with dating the file (when using format mp3) from what I am seeing.  I'm happy to try things and see what we find.

**Comment by nlogozzo** [comment]
Could you go into preferences of Tube Converter and turn off `Embed Metadata` and see if that fixes it...

**Comment by Tater-K7S5A** [comment]
That seems to work.  No thumbnail, though.

**Comment by nlogozzo** [comment]
Tube Converter adds the flags `--add-metadata --embed-thumbnail` to a file when `Embed Metadata` is on. Can you see if the issue occurs when these flags are used with `youtube-dl` and `yt-dlp` outside Tube Converter. If that's the case then it's a problem with Youtube-dl and how it saves the metadata to the mp3.

**Comment by Tater-K7S5A** [comment]
Thank you for your assistance with this.  I just got up and ran the following:

`yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 --add-metadata --embed-thumbnail https://www.youtube.com/watch?v=[video id]`

Which yielded an mp3 with thumbnail but a date of 1/1/22.

`youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --add-metadata --embed-thumbnail https://www.youtube.com/watch?v=[video id]`

Which yielded an mp3 with thumbnail and a correct date (date of download).

So it appears the yt-dlp fork has an issue.  Off to their Github page I go.

**Comment by Tater-K7S5A** [comment]
OK.  That was interesting.  I am not sure whether I am able to submit a bug report or not because they seem extra prickly about getting anything wrong.  I'll pass on it.

Thank you for the assistance and for your great project!  I'll just close this issue now since I have concluded it is a yt-dlp issue and not yours.
