### ISSUE TITLE
The app can read/write all data

### ISSUE THREAD

**Issue by ghost** [nlogozzo/NickvisionTubeConverter#39]
The app is labeled as unsafe by GNOME Software because of this. I don't feel very comfortable with this level of access and I think other users might think the same. Perhaps this can be reconsidered?

## Additional info
- Tube Converter 2022.11.1
- Fedora 37 Workstation

**Comment by nlogozzo** [comment]
It has access to the user's home directory. This is to allow `yt-dlp` access to download files wherever a user may choose. 
I will look into seeing if I could reduce the permissions further.

In previous testing, however, if I restricted permissions to lets just say the Downloads directory and a user picked any other directory in their home directory, through the file picker, the application would fail to download to that location. 
Hence why Tube Converter requests access to the whole home directory.

**Comment by nlogozzo** [comment]
> Can portals solve this problem?

The application already uses xdg portals via GtkFileChooserNative so I don't get way it doesn't work. Maybe since yt-dlp get executed in a separate process and doesn't follow the xdg specs.

The application is getting a rewrite soon in C# which will replace yt-dlp with a proper C# YouTube backend, meankng hopefully this problem will be fixed and the permissions can be reduced.

**Comment by fsobolev** [comment]
> The application is getting a rewrite soon in C# which will replace yt-dlp with a proper C# YouTube backend, meankng hopefully this problem will be fixed and the permissions can be reduced.

I guess we'll need to get and pass the portal provided file path to the yt-dlp.

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.FileChooser
> The FileChooser portal allows sandboxed applications to ask the user for access to files outside the sandbox. The portal backend will present the user with a file chooser dialog.
The selected files will be made accessible to the application via the document portal, and the returned URI will point into the document portal fuse filesystem in /run/user/$UID/doc/.

**Comment by DaPigGuy** [comment]
I've been running Tube Converter without any file permissions for a while with no issues :raised_eyebrow:
