### ISSUE TITLE
Show download log while downloading a video

### ISSUE THREAD

**Issue by Anikmoujegy** [nlogozzo/NickvisionTubeConverter#40]
As I see after downloading or canceling a video I user can see the download log so it will be so great if you add option to view download logs at the time of downloading video.....

**Comment by nlogozzo** [comment]
As of now I can only collect the download log from the terminal after the download completes. 

However Tube Converter is getting a full rewrite in C# which may allow for this feature.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-beta2
