### ISSUE TITLE
Add ability to open save folder when completed

### ISSUE THREAD

**Issue by esa1975** [nlogozzo/NickvisionTubeConverter#41]
Hello. First, this is a very well done program that I enjoy using and thank you for making. One thing that I would like to have is the ability to open the save folder when the item has completed. Perhaps add a button or the ability to click the save path in the item entry. Please let me know if there is any further information I can provide. Thanks again and happy new year to you!

**Comment by nlogozzo** [comment]
Will add for the next version :)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/218324709-15baaf9b-70ae-4f36-8ff7-ed2823926cec.png)

You can see the folder icon in the row when a download is finished that will open the save folder of that download :)

**Comment by esa1975** [comment]
Wonderful! Thank you very much.

**Comment by nlogozzo** [comment]
I'm hoping to release a beta version of 2023.2.1 either today or tomorrow so you can start testing and using these new features!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-beta1-p1

**Comment by esa1975** [comment]
Hello again. I wasn't sure if this was the right place to leave a comment but the new feature works perfectly. Thank you for adding it!
