### ISSUE TITLE
Unsable to add job when New FIlename is empty

### ISSUE THREAD

**Issue by esa1975** [nlogozzo/NickvisionTubeConverter#42]
I see this issue referenced in #32 which is closed. I guess I have been adding a new filename each time I have used Tube Converter until today. When I tried to leave it blank, I was given a "Save Folder (Invalid)" error. I tried the same download but added a new filename and it works as expected. I know you said that a blank filename shouldn't make a difference but it definitely does in my case.

Please note that I do not consider this to be a showstopper by any means. I am fine putting in a new filename for now. Just thought you should know.

Version: 2022.11.1 (flatpak)
Debug Info:
Dependencies:
- yt-dlp Version 2022.10.04
- ffmpeg Version 5.1.2

Please let me know if there is anything else I can provide. Thanks!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2023.3.0-beta1-p1
