### ISSUE TITLE
Snap package is ready!!!

### ISSUE THREAD

**Issue by soumyaDghosh** [nlogozzo/NickvisionTubeConverter#47]
Hi, I have made a snap for your app and  I'm ready to maintain it. Would u like to check it out?

**Comment by nlogozzo** [comment]
Looks good! Thanks for maintaining it :)

**Comment by fsobolev** [comment]
@soumyaDghosh 
Not only C# rewrite of the app, but also changes in #58 radically change how the app is built. I have no experience in creating snaps, so I can't help you with any instructions, but I hope I can give you some hints to update snap.
1. There's [dotnet snapcraft plugin](https://snapcraft.io/docs/dotnet-plugin).
2. yt-dlp is now used as python module, not a separate binary, this may require some changes in building.
3. [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) and [Just](https://github.com/casey/just) are new build dependencies.
4. `just` is used as some kind of build system. To build self-contained app, you can run `just publish-self-contained PREFIX`. If it doesn't fit your needs and you need another recipe to build snap, you can create a PR to add `publish-snap` recipe into `justfile` (there's a separate recipe for flatpak - `publish-flatpak` - so I see no problem in having another one for snap).

Feel free to ask any questions, I will be happy to help :)

**Comment by soumyaDghosh** [comment]
How should I build the app using `just`, can you give me the command?

**Comment by fsobolev** [comment]
> How should I build the app using `just`, can you give me the command?

```
cd NickvisionTubeConverter.GNOME
just publish-self-contained /usr
just install INSTALL_DIR
```

Replace `/usr` with another prefix if needed. `INSTALL_DIR` should be the path where to install files, use whatever is appropriate for Snap. Examples for other packaging formats: for Flatpak it's `/` (to place everything in the flatpak root), and for AUR it's `$pkgdir` (to place everything in the directory from which the package is created).

**Comment by soumyaDghosh** [comment]
Let's say the `INSTALL_DIR` is `/root/prime/`, then if the prefix is kept as `/usr` then there will be a folder created as `/root/prime/usr`

**Comment by fsobolev** [comment]
> Let's say the `INSTALL_DIR` is `/root/prime/`, then if the prefix is kept as `/usr` then there will be a folder created as `/root/prime/usr`

Right, and the files will be:
> /root/prime/usr/bin/org.nickvision.tubeconverter
/root/prime/usr/share/applications/org.nickvision.tubeconverter.desktop
/root/prime/usr/share/org.nickvision.tubeconverter/org.nickvision.tubeconverter.gresource
/root/prime/usr/lib/org.nickvision.tubeconverter/NickvisionTubeConverter.dll
etc

**Comment by fsobolev** [comment]
@soumyaDghosh We found out that the icon we use for logs button doesn't fit the meaning in Yaru icon theme and probably some other, so in #87 it was hardcoded. Screenshot there shows how the app looks with Yaru icons, and Adwaita icon looks out of style. If you think this is an issue, the suggestion is to replace the icon in Snap package with what was used in old version of the app:
```
sed -i "s/tubeconverter-logs/dialog-information/g" NickvisionTubeConverter.GNOME/Blueprints/download_row.blp
```
This icon will probably look good no matter what Ubuntu flavor a user has installed and what the icon theme is.
But it's up to you, if you think it's okay currently you can leave it as is.

**Comment by soumyaDghosh** [comment]
I will take a look into that. Also, 
Is `liblttng-ust` necessary for your app?

**Comment by nlogozzo** [comment]
> Is liblttng-ust necessary for your app?

I've never heard of that library, nor do we download it anywhere for flatpak, so I'd say no. Unless it's a dependency for `yt-dlp`, but i don't think it is, but not 100% sure.

**Comment by soumyaDghosh** [comment]
Well, biggest issue is, when I'm running it, I'm getting `Unhandled exception.` What can be the reason behind?

**Comment by nlogozzo** [comment]
most likely resource files are not installed correctly...let me wrap the application in a try catch so it will print an error message...

**Comment by nlogozzo** [comment]
try the latest commit in main and see what error message it gives...

**Comment by soumyaDghosh** [comment]
Can I try it later?

**Comment by nlogozzo** [comment]
yeah no rush :)

**Comment by soumyaDghosh** [comment]
Actually on my way to my college and without my lappy... Rushing in😑

**Comment by soumyaDghosh** [comment]
> yeah no rush :)

No, yet I'm getting `Unhandled exception.`

**Comment by soumyaDghosh** [comment]
I think that's an issue of dotnet
