### ISSUE TITLE
C# Rewrite

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTubeConverter#49]

**Comment by soumyaDghosh** [comment]
Why C#? Like, I just started learning C++, so, I'd contribute in your project. But you're rewriting it. Badd :-(

**Comment by nlogozzo** [comment]
C# is better suited for our needs of the application. It provides much cleaner and more readable code. We can implement features a lot faster with its wide range of libraries. And we're also able to bring our apps to other platforms easier.

C# isn't widely different from C++, so it shouldn't been that hard to pickup as most of our other contributors did.

C++ was just too cumbersome for us. Many GTK apps are written in python and Vala (GTK's version of C#) because C/C++ is unnecessarily complicated at times.

**Comment by nlogozzo** [comment]
Of course if you'd like to make your contributions to the new version and need help with some C# syntaxes and implementation....feel free to ask :) we're always willing to help!

**Comment by fsobolev** [comment]
> C# isn't widely different from C++, so it shouldn't been that hard to pickup as most of our other contributors did.

I started to learn C++ to contribute to Denaro (back then it was called Money) and then switched to C# when Nick decided to rewrite the app. Before that I have been programming in Python only.
It's much easier to write GTK apps in C#, even tho gir.core (C# bindings for GTK and other libraries) is still in pretty much alpha state. Code is cleaner and shorter, and we got rid of some absurd problems we had with C++.
@soumyaDghosh, we'll be happy to see you contributing to the project, and we'll provide you with any help you need for that. Feel free to join [our Matrix channel](https://matrix.to/#/#nickvision:matrix.org).

**Comment by soumyaDghosh** [comment]
TBH honest, I have just started learning C++, anyways, I can already see very less difference in C & C++, but I am really amazed with both of your help. Thanks a lot. I will really try asap, currently, I am very much into snaps also. And my first published snap is for your snap, which within these days has got almost 200+ active user. So cheers.

![image](https://user-images.githubusercontent.com/72045785/219884647-394c5a35-bda5-441f-a564-2074cfc1ad8b.png)
