### ISSUE TITLE
Make UI Translateable

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionTubeConverter#5]

**Comment by ovari** [comment]
Please use [Hosted Weblate](https://hosted.weblate.org/) as it will enable translation using a web browser.

**Comment by nlogozzo** [comment]
Translation support is here! https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.11.0-beta1

**Comment by nlogozzo** [comment]
Please submit a PR with your translations by Nov 10, 2022 to be included in the V2022.11.0 stable release for this week.

**Comment by ovari** [comment]
Can you please add a `hu` (Hungarian - magyar) file with the en source strings and blank hu strings which we can add the translations to?

Thank you

**Comment by ovari** [comment]
Is the `desktop`, `appdata` and `xml` files included in the translation? Cf. https://github.com/xournalpp/xournalpp#translations

**Comment by nlogozzo** [comment]
Please look at the `Translating` section of the README for information on how to translate to your language.

**Comment by ovari** [comment]
> Please look at the `Translating` section of the README for information on how to translate to your language.

Thanks for the hint; however, seems too technical as we don't have `meson` and are not fluent with building software.

Unfortunately, will have to wait for a web-browser based translation solution, like [Hosted Weblate](https://hosted.weblate.org/).

Thank you once again.

**Comment by nlogozzo** [comment]
Thank you everyone for your help with translating this application, making it accessible to more people than ever before. A stable release will be released this week by Nov 10, 2022 with your translations :)
I'm closing this issue as completed since the translation infrastructure is complete.
