### ISSUE TITLE
[Feature Request] Split video by chapters

### ISSUE THREAD

**Issue by not-a-dev-stein** [nlogozzo/NickvisionTubeConverter#551]
yt-dlp has a really neat feature in `--split-chapters` where it... splits the video you link into several smaller videos, splitting them by their chapters.

This could come pretty handy in situations [like we had in Flock to Fedora](https://gitlab.com/fedora/marketing/marketing-planning/-/issues/72) or [for future GUADECs](https://ursal.zone/@cassidy@blaede.family/110908774876354553), making the process of taking individual talks from a single livestreamed event could be made much easier.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Parabolic/releases/tag/2023.8.3-rc1

*should be on flathub beta soon...whenever gnome gitlab is up again*
