### ISSUE TITLE
Use same symbol across all icons

### ISSUE THREAD

**Issue by martin-desktops** [nlogozzo/NickvisionTubeConverter#6]
Replace the symbol used in the app icon by the TubeConverter's symbolic icon, so it looks constantly across all variants.

Here are my editing attempts results:

![org nickvision tubeconverter](https://user-images.githubusercontent.com/64419373/195626152-92ca0ac5-6f4b-492b-b747-785efcf7cb9f.svg)
![org nickvision tubeconverter-devel](https://user-images.githubusercontent.com/64419373/195626161-98c2db4e-8f72-437e-b2ff-c5999b83bcef.svg)

**Comment by nlogozzo** [comment]
Love it! Thank you...i'll include it in the next release.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/commit/8f820b2baaf4f2a9ac0e3d27f7500c6b1633ea3c

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2-beta1

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2
