### ISSUE TITLE
Better handling with YouTube URLs

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#7]
The app don't understand the short version of YouTube URLs.
![image](https://user-images.githubusercontent.com/93544997/195801453-050186b4-1084-4dfb-8e64-2b2deae1c506.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2-beta1

**Comment by nlogozzo** [comment]
Please test the beta version and let me know how it goes.

**Comment by fawaz006** [comment]
I tried it, and it just works as expected 👍

**Comment by nlogozzo** [comment]
A stable release should come this weekend.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2
