### ISSUE TITLE
Auto enter video name.

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#8]
![image](https://user-images.githubusercontent.com/93544997/195940698-37f7a305-89ba-4cf5-94fa-4a351e09df84.png)

**Comment by nlogozzo** [comment]
I will make it where an empty new filename will default to the video title.

**Comment by nlogozzo** [comment]
Please test: https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2-beta3

**Comment by nlogozzo** [comment]
If all looks well, I will release the stable version.

**Comment by fawaz006** [comment]
It works perfectly👍, but can you check #9 before release the stable version (Sorry if I bothered you)

**Comment by nlogozzo** [comment]
No bother at all, I greatly appreciate all the testing and feedback you are providing! I will take a look.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionTubeConverter/releases/tag/2022.10.2
