### ISSUE TITLE
Paste button?

### ISSUE THREAD

**Issue by fawaz006** [nlogozzo/NickvisionTubeConverter#9]
I't well be great if you add a button near “Add” to auto paste and download the video with the default setting and without showing the download window, or add it on the setting as an option 👍

**Comment by nlogozzo** [comment]
Interesting feature, I will think about how to design this and maybe implement it.

**Comment by nlogozzo** [comment]
After further consideration, I will not be implementing this feature. Tube Converter already makes it very easy to accomplish this task, just click `Add` and paste the link and start the download. Your previous settings will be used and if no `New Filename` is provided the video title will be used. No need to over simplify an already very simple task.
